
package Ventanas.cliente;

import javax.swing.JFrame;

public class ticket extends javax.swing.JFrame {

    public ticket(String idTransaccion, String idCuenta, String idEmpleado, String tipoTransaccion, String descripcion, double montoDeposito, String idCuentaRecibir) {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        String tickettext="<html>" +
            "<div style='font-family:Arial, sans-serif; font-size:14px;'>" +
            "<h2 style='text-align:center; margin-bottom:10px;'>Detalles de la Transacción</h2>" +
            "<hr style='border:1px solid #000; margin-bottom:10px;'/>" +
            "<p><strong>ID Transacción:</strong> " + idTransaccion + "</p>" +
            "<hr style='border:1px solid #ccc; margin-bottom:10px;'/>" +
            "<p><strong>ID Cuenta:</strong> " + idCuenta + "</p>" +
            "<hr style='border:1px solid #ccc; margin-bottom:10px;'/>" +
            "<p><strong>ID Empleado:</strong> " + idEmpleado + "</p>" +
            "<hr style='border:1px solid #ccc; margin-bottom:10px;'/>" +
            "<p><strong>Tipo Transacción:</strong> " + tipoTransaccion + "</p>" +
            "<hr style='border:1px solid #ccc; margin-bottom:10px;'/>" +
            "<p><strong>Descripción:</strong> " + descripcion + "</p>" +
            "<hr style='border:1px solid #ccc; margin-bottom:10px;'/>" +
            "<p><strong>Monto:</strong> " + String.format("%.2f", montoDeposito) + "</p>" +
            "<hr style='border:1px solid #ccc; margin-bottom:10px;'/>" +
            "<p><strong>Cuenta Receptora:</strong> " + idCuentaRecibir + "</p>" +
            "<hr style='border:1px solid #ccc; margin-bottom:10px;'/>" +
            "</div></html>";
            verRegistro.setText(tickettext);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        verRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        verRegistro.setBackground(new java.awt.Color(255, 255, 255));
        verRegistro.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        verRegistro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(verRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(verRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel verRegistro;
    // End of variables declaration//GEN-END:variables
}
